use std::collections::HashMap;

use eyre::{bail, eyre, WrapErr};
use serde::Serialize;

use crate::{
    compiler::section::HTMLContent, config, entry, environment, ordered_map::OrderedMap, slug::Slug,
};

#[derive(clap::Args)]
pub struct SnipCommand {
    /// Path to the configuration file (e.g., "Kodama.toml").
    #[arg(short, long, default_value_t = config::DEFAULT_CONFIG_PATH.into())]
    config: String,

    /// Generate `.vscode/katex.code-snippets`.
    #[arg(long)]
    katex: bool,

    /// Generate `.vscode/section.code-snippets`.
    #[arg(long)]
    section: bool,

    /// Generate `.vscode/inline-section.code-snippets`.
    #[arg(long)]
    inline_section: bool,
}

#[derive(Serialize)]
struct Snippet {
    scope: &'static str,
    prefix: String,
    body: [String; 1],
    description: String,
}

impl Snippet {
    fn new(scope: &'static str, prefix: String, body: [String; 1], description: String) -> Self {
        Self {
            scope,
            prefix,
            body,
            description,
        }
    }

    fn md(prefix: String, body: [String; 1], description: String) -> Self {
        Self::new("markdown", prefix, body, description)
    }
}

/// This function invokes the [`environment::init_environment`] function to initialize the environment
pub fn snip(command: &SnipCommand) -> eyre::Result<()> {
    let config_path = &command.config;
    environment::init_environment(config_path.into(), environment::BuildMode::Serve)?;

    if command.section {
        section_snippets()?;
    }

    if command.katex {
        katex_snippets()?;
    }

    if command.inline_section {
        inline_section_snippets()?;
    }

    Ok(())
}

fn section_snippets() -> eyre::Result<()> {
    let output_dir = environment::root_dir().join(environment::serve_dir());
    let indexes_path = environment::indexes_path(&output_dir);

    // Check if the indexes file exists
    if !indexes_path.exists() {
        bail!("Indexes file not found. Please run `kodama serve` first.");
    }

    let indexes_content = std::fs::read_to_string(&indexes_path)
        .wrap_err_with(|| eyre!("Failed to read indexes file at `{}`", indexes_path))?;
    let indexes: HashMap<Slug, OrderedMap<String, HTMLContent>> =
        serde_json::from_str(&indexes_content)
            .wrap_err_with(|| eyre!("Failed to parse indexes JSON from `{}`", indexes_path))?;

    let snippets: HashMap<&str, Snippet> = indexes
        .iter()
        .filter_map(|(slug, metadata)| {
            let prefix = metadata.get(entry::KEY_TITLE)?.remove_all_tags();
            let slug_str = slug.as_str();
            let ext = metadata.get(entry::KEY_EXT)?.as_str()?;
            let trees_dir = environment::trees_dir_without_root();
            let url = format!("/{}/{}.{}", trees_dir, slug_str, ext);

            let label = prefix
                .to_lowercase()
                .split_whitespace()
                .collect::<Vec<_>>()
                .join("-");
            let body = [format!("[{label}]: {url}")];
            let taxon = metadata.get(entry::KEY_TAXON)?.as_str()?;
            let description = taxon.to_string();

            Some((slug_str, Snippet::md(prefix.to_string(), body, description)))
        })
        .collect();

    let snippets_path = environment::root_dir()
        .join(".vscode")
        .join("section.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    let serialized = serde_json::to_string_pretty(&snippets)
        .wrap_err_with(|| eyre!("failed to serialize snippets to JSON"))?;
    std::fs::write(&snippets_path, serialized)
        .wrap_err_with(|| eyre!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}

fn katex_snippets() -> eyre::Result<()> {
    let snippets_path = environment::root_dir()
        .join(".vscode")
        .join("katex.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    // Generated by: https://github.com/kodama-community/vscode-katex-snippets
    let json = include_str!("../include/katex-snippets.json");
    std::fs::write(&snippets_path, json)
        .wrap_err_with(|| eyre!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}

fn inline_section_snippets() -> eyre::Result<()> {
    let snippets_path = environment::root_dir()
        .join(".vscode")
        .join("inline-section.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    let json = include_str!("../include/inline-section-snippets.json");
    std::fs::write(&snippets_path, json)
        .wrap_err_with(|| eyre!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}
